<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/4/17
 * Time: 12:00
 * Comment: 数据管理
 */
namespace app\admin\controller;

use app\common\controller\Backend;

class Data extends Backend {

    /**
     * 声明model
     */
    protected $model = null;

    /**
     * 初始化
     */
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->model = model('Data');
    }

    /**
     * 导入
     */
    protected function import()
    {
    }


}