<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/4/17
 * Time: 13:00
 * Comment: 直播平台管理控制器
 */
namespace app\admin\controller\data;

use app\common\controller\Backend;

class Platform extends Backend {

    /**
     * 声明模型
     */
    protected $model = null;

    /**
     * 初始化
     */
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->model = model('Platform');
    }

    /**
     * 导入
     */
    protected function import()
    {

    }
}